/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static merge.sort.Library.sort;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
  public void testMergeSortEmptyArr() {
      int[] arr = new int[]{};
      try {
        sort(arr,0,arr.length-1);
      }catch (Exception e)
      {
        arr = new int[]{e.hashCode()};
      }
    assertEquals(sort(arr,0,arr.length-1),arr);
      assertEquals(Arrays.toString(sort(arr,0,arr.length-1)),Arrays.toString(arr));

  }
  @Test
  public void testMergeSortNonEmptyArr() {
    int[] arr = new int[]{14,18,2,9,71,54,60};
    try {
      sort(arr,0,arr.length-1);
    }catch (Exception e)
    {
      arr = new int[]{e.hashCode()};
    }
    assertEquals(sort(arr,0,arr.length-1),arr);
    assertEquals(Arrays.toString(sort(arr,0,arr.length-1)), "[2, 9, 14, 18, 54, 60, 71]");
  }
}
