/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
  @Test
  public void testFindFirstRepeatedWord() {
    String test1 = "When I was young, I used to go to school.";
    String test2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
    String test3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
    String test4 = "There are no repeated words in this string, so return null. Thank you.";
    String test5 = "ThisStringHasNoSpacesButDoesHaveThisRepeatedWord";
    String test6 = "";
    assertEquals("I", Library.repeatedWord(test1), "Should return the second instance of the first repeated word.");
    assertEquals( "it", Library.repeatedWord(test2), "Should return the second instance of the first repeated word. Note the first 'It' is capitalized, and second 'it' is not.");
    assertEquals( "summer", Library.repeatedWord(test3),"Trailing punctuation should not be compared.");
    assertEquals(null, Library.repeatedWord(test4),"If there are no repeated words, it should return 'null'.");
    assertEquals( null, Library.repeatedWord(test5),"This should return 'null' since there are no spaces between the words..");
    assertEquals( null, Library.repeatedWord(test6),"An empty string should also return 'null' and not break anything in the process.");
  }
}
