/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static insertion.sort.Library.insertionSort;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
  @Test
  public void testInsertionSortEmptyArr() {
    int[] arr = new int[]{};
    try {
      insertionSort(arr);
    }catch (Exception e)
    {
      arr = new int[]{e.hashCode()};
    }
    assertEquals(insertionSort(arr),arr);
    assertEquals(Arrays.toString(insertionSort(arr)),Arrays.toString(arr));

  }
  @Test
  public void testInsertionSortNonEmptyArr() {
    int[] arr = new int[]{14,18,2,9,71,54,60};
    try {
      insertionSort(arr);
    }catch (Exception e)
    {
      arr = new int[]{e.hashCode()};
    }
    assertEquals(insertionSort(arr),arr);
    assertEquals(Arrays.toString(insertionSort(arr)), "[2, 9, 14, 18, 54, 60, 71]");
  }
}
